### ISSUE TITLE
Error "Missing setXAxis" method on new generated charts

### ISSUE THREAD

**Issue by callmemark** [marineusde/larapex-charts#27]
![image](https://github.com/user-attachments/assets/25f8baae-4285-4d7b-9ea9-2f7ef00fd58e)

### Description:
On a new generated chart file, it includes a setXAxis() method call which results in error  "Call to undefined method marineusde\LarapexCharts\Charts\BarChart::setXAxis()".

### Steps to Reproduce: 
php artisan make:chart MyChartName
Create new chart. The missing method call is already on the generated chart.

### Workaround to make it work: 

I added the **"use marineusde\LarapexCharts\Options\XAxisOption;"** and instead of 

public function build(): OriginalBarChart
    {
        return (new OriginalBarChart)
            ->setTitle('San Francisco vs Boston.')
            ->setSubtitle('Wins during season 2021.')
            ->addData('San Francisco', [6, 9, 3, 4, 10, 8])
            ->addData('Boston', [7, 3, 8, 2, 6, 4])
            **->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);**
    }   
    
  I changed the  **setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);** line into  **setXAxisOption(new XAxisOption(['January', 'February', 'March', 'April', 'May', 'June']));**

**Comment by marineusde** [comment]
thanks for the report, fixed in #29 and released in version 1.4.2
