### ISSUE TITLE
Call to undefined method container()

### ISSUE THREAD

**Issue by ramakun-69** [marineusde/larapex-charts#28]

**Comment by marineusde** [comment]
can you insert your code or command please, so I can reproduce it?

**Comment by ramakun-69** [comment]
![Screenshot (29)](https://github.com/user-attachments/assets/ba624e76-d865-4a57-bade-74a425bd438c)

**Comment by ramakun-69** [comment]
![Screenshot (30)](https://github.com/user-attachments/assets/c28d6416-dd69-4c37-a22d-af78247d0cbe)

**Comment by ramakun-69** [comment]
![image](https://github.com/user-attachments/assets/045f7f56-27b4-473c-928c-90574a177ccb)

**Comment by ramakun-69** [comment]
![image](https://github.com/user-attachments/assets/9df709d8-82f6-4357-9936-e453f69bd1e7)

**Comment by marineusde** [comment]
Thank you! Cause your Ranking-Chart-Class is not the Chart itself, you have to return the build()-Method to return the BarChart-Object in your controller:

```
return view('dashboard', ['title' -> $title, 'chart' => $chart->build()]) 
```

If you create it in the controller is easy too:
```
public function index()
{
   return view('dashboard', ['title' => __('Dashboard'), 'chart' => $this->getChart()]
}

private function getChart(): BarChart
{
  return (new BarChart())
            ->setTitle('San Fransisco vs Boston.')
            ->setSubtitle('Wins during seasons 2021.')
            ->addData('San Francisco', [6, 9, 3, 4, 10, 8])
            ->addData('Boston', [7, 3, 8, 2, 6, 4])
            ->setXAxisOption(new XAxisOption(['January', 'February', 'March', 'April', 'May', 'June']));
}
```

Hint: You can test this and other problems in blade files with to check its the correct class:

```
{!! get_class($chart) !!}
```

I hope I could help you :)

**Comment by ramakun-69** [comment]
Okkeh thanks
